### ISSUE TITLE
Can we provide Waypoints ? and also pre feed the coordinates of end and start location ?

### ISSUE THREAD

**Issue by aditbharadwaj** [neeleshbisht99/react-map-gl-directions#1]

**Comment by neeleshbisht99** [comment]
Hey Aditbhardwaj, react-map-gl-directions package is deprecated now, sorry for the inconvinience. 
I will suggest you try using [mapbox-gl-directions](https://github.com/mapbox/mapbox-gl-directions). 
Thanks
