### ISSUE TITLE
Route with multiple points (steps)

### ISSUE THREAD

**Issue by Devmaticz** [neeleshbisht99/react-map-gl-directions#10]
Hello, 

Does the library can be used to design a route with multiple points (steps), 

My goal is designing a route planner using react map Gl.

Best

**Comment by neeleshbisht99** [comment]
Thanks for looking into react-map-gl-directions, but I'm sorry to say that it has been deprecated now & can't be used anymore.
Instead I'll suggest you use mapbox-gl-directions plugins.
Here :https://github.com/mapbox/mapbox-gl-directions

Thanks
