### ISSUE TITLE
no versions available for react-map-directions?

### ISSUE THREAD

**Issue by jamesvovos** [neeleshbisht99/react-map-gl-directions#11]
everytime I run the command "npm install --save react-map-gl-directions" I get an error saying that there are no versions available for react-map-gl-directions? Is there a fix?
![errrrrr](https://user-images.githubusercontent.com/79495095/167568896-1c602219-9a47-4e6a-9008-20a7bbc8982d.PNG)

**Comment by TGChrisRArendt** [comment]
I have the same issue, thanks for posting

**Comment by neeleshbisht99** [comment]
Thanks for looking into react-map-gl-directions, but I'm sorry to say that it has been deprecated now & can't be used anymore. 
Instead I'll suggest you use mapbox-gl-directions plugins.
Here :https://github.com/mapbox/mapbox-gl-directions

Thanks
